"""
Statement PDF Generator
Generates a professional account statement for any party.
Uses only stdlib + reportlab (lightweight).
Falls back to plain HTML if reportlab not installed.
"""
from datetime import date
from decimal import Decimal
from typing import List, Optional
import io


def generate_html_statement(party_name, party_gst, business_name, transactions,
                              from_date, to_date, opening_balance, closing_balance) -> str:
    rows_html = ""
    running = opening_balance
    for t in transactions:
        is_increase = t["transaction_type"] in ("bill", "sale")
        running = running + Decimal(str(t["amount"])) if is_increase else running - Decimal(str(t["amount"]))
        amount_str = f"₹{abs(float(t['amount'])):,.0f}"
        color = "#E8542C" if is_increase else "#1F6E5C"
        rows_html += f"""
        <tr>
            <td>{t['transaction_date']}</td>
            <td style="color:{color}">{t['transaction_type'].replace('_',' ').title()}</td>
            <td>{t.get('notes') or '—'}</td>
            <td style="text-align:right;color:{color}">{amount_str}</td>
            <td style="text-align:right;font-weight:600">₹{abs(float(running)):,.0f}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family: 'Inter', Arial, sans-serif; color: #0B0F0D; background: #F7F5F0; padding: 40px; }}
  .header {{ display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:40px; padding-bottom:20px; border-bottom:2px solid #0B0F0D; }}
  .brand {{ font-size:28px; font-weight:600; }}
  .brand span {{ color:#E8542C; }}
  .meta {{ text-align:right; font-size:13px; color:#8A8478; line-height:1.8; }}
  .party-block {{ background:#EFEAE0; border-radius:4px; padding:20px; margin-bottom:30px; display:flex; justify-content:space-between; }}
  .party-block h2 {{ font-size:20px; margin-bottom:4px; }}
  .party-block p {{ font-size:13px; color:#8A8478; }}
  .summary {{ display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-bottom:30px; }}
  .summary-card {{ background:#fff; border:1px solid #D9D2C3; border-radius:4px; padding:16px; }}
  .summary-card p {{ font-size:11px; text-transform:uppercase; letter-spacing:0.1em; color:#8A8478; margin-bottom:6px; }}
  .summary-card h3 {{ font-size:22px; font-weight:600; }}
  table {{ width:100%; border-collapse:collapse; font-size:13px; }}
  th {{ background:#0B0F0D; color:#F7F5F0; text-align:left; padding:10px 14px; font-size:11px; text-transform:uppercase; letter-spacing:0.1em; font-weight:500; }}
  td {{ padding:10px 14px; border-bottom:1px solid #D9D2C3; }}
  tr:nth-child(even) {{ background:#EFEAE0; }}
  .footer {{ margin-top:30px; text-align:center; font-size:11px; color:#8A8478; }}
  @media print {{ body {{ background:white; padding:20px; }} .summary-card {{ background:#f5f5f5; }} }}
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="brand">Bakaaya<span>.</span></div>
    <p style="font-size:13px;color:#8A8478;margin-top:4px">Account Statement</p>
  </div>
  <div class="meta">
    <strong>{business_name}</strong><br>
    Period: {from_date} to {to_date}<br>
    Generated: {date.today().strftime('%d %b %Y')}
  </div>
</div>

<div class="party-block">
  <div>
    <h2>{party_name}</h2>
    {f'<p>GST: {party_gst}</p>' if party_gst else ''}
  </div>
  <div style="text-align:right">
    <p style="font-size:11px;color:#8A8478;margin-bottom:4px">CLOSING BALANCE</p>
    <p style="font-size:28px;font-weight:600;color:{'#E8542C' if closing_balance > 0 else '#1F6E5C'}">₹{abs(float(closing_balance)):,.0f}</p>
  </div>
</div>

<div class="summary">
  <div class="summary-card">
    <p>Opening Balance</p>
    <h3>₹{abs(float(opening_balance)):,.0f}</h3>
  </div>
  <div class="summary-card">
    <p>Total Transactions</p>
    <h3>{len(transactions)}</h3>
  </div>
  <div class="summary-card">
    <p>Closing Balance</p>
    <h3 style="color:{'#E8542C' if closing_balance > 0 else '#1F6E5C'}">₹{abs(float(closing_balance)):,.0f}</h3>
  </div>
</div>

<table>
  <thead>
    <tr><th>Date</th><th>Type</th><th>Notes</th><th style="text-align:right">Amount</th><th style="text-align:right">Balance</th></tr>
  </thead>
  <tbody>{rows_html}</tbody>
</table>

<div class="footer">
  Generated by Bakaaya · {date.today().strftime('%d %B %Y')} · This is a computer-generated statement.
</div>
</body>
</html>"""
